"""
xbench.py
---------
Xbench Excel report parser, filter, and RAG case importer.

Usage:
    python xbench.py <file.xlsx>                        parse → show summary
    python xbench.py <file.xlsx> --keep 12,15,20        keep only listed rows, save _filtered.xlsx
    python xbench.py <file.xlsx> --import               parse and insert all rows into RAG case library
    python xbench.py <file.xlsx> --import --annotator 张三   specify annotator (default: 宋莹莹)
"""

import json
import re
import os
import sys

import openpyxl

# ══════════════════════════════════════════════════════════════════════════════
# Row-type detection
# ══════════════════════════════════════════════════════════════════════════════

_KNOWN_CHECK_TYPES = [
    "Key Term Mismatch",
    "Inconsistency in Source",
    "Inconsistency in Target",
    "Untranslated Segments",
    "Target same as Source",
    "Tag Mismatch",
    "Numeric Mismatch",
    "URL Mismatch",
    "Alphanumeric Mismatch",
    "ALLUPPERCASE Mismatch",
    "CamelCase Mismatch",
    "Leading/Trailing Mismatch",
    "Unpaired Symbol",
    "Unpaired Quotes",
    "Double Blank",
    "Repeated Word",
    "Repeated Words",
    "Segments with Comments",
]

_RE_DATA_ROW = re.compile(r".+\s+\(\d+\)$")
_RE_TERM_PAIR = re.compile(r"\([^)]*/.+\)")

_SKIP_PREFIXES = (
    "Exported QA Report", "ApSIC XBench", "http://",
    "Selected QA Checks", "Basic", "Content",
    "Key Term Glossaries", "Checklists", "Generated by",
    "Source", "Target", "Comments", "Metadata", "Project Checklist",
)


def _clean(val: object) -> str:
    if val is None:
        return ""
    return str(val).strip()


def _is_skip(a: str) -> bool:
    if not a:
        return True
    low = a.lower()
    return any(low.startswith(p.lower()) for p in _SKIP_PREFIXES)


def _is_group_header(a: str) -> bool:
    if _RE_DATA_ROW.match(a):
        return False
    if _RE_TERM_PAIR.search(a):
        return True
    low = a.lower()
    return any(low.startswith(ct.lower()) for ct in _KNOWN_CHECK_TYPES)


def _is_data_row(a: str) -> bool:
    return bool(_RE_DATA_ROW.match(a))


# ══════════════════════════════════════════════════════════════════════════════
# Parser
# ══════════════════════════════════════════════════════════════════════════════

def parse(path: str) -> list[dict]:
    """Parse Xbench Excel. Returns one dict per data row.

    Keys: row_num, check_type, term_zh, term_en, error_description,
          source_text, target_text, comments_raw, metadata,
          file_name, segment_id, annotation
    annotation: raw value from col6/col7 annotation column (e.g. "已修改"), or "".
    """
    wb = openpyxl.load_workbook(path)
    ws = _pick_sheet(wb)
    rows = []
    ct = zh = en = ""

    for r in range(11, ws.max_row + 1):
        a = _clean(ws.cell(r, 1).value)
        if _is_group_header(a):
            ct, zh, en = _parse_group_header(a)
            continue
        if _is_skip(a):
            continue
        if _is_data_row(a):
            fn, sid = _parse_data_row_a(a)
            c6 = _clean(ws.cell(r, 6).value)
            c7 = _clean(ws.cell(r, 7).value)
            annotation = "已修改" if "已修改" in c6 or "已修改" in c7 else ""
            rows.append({
                "row_num":           r,
                "check_type":        ct,
                "term_zh":           zh,
                "term_en":           en,
                "source_text":       _clean(ws.cell(r, 3).value),
                "target_text":       _clean(ws.cell(r, 4).value),
                "comments_raw":      _clean(ws.cell(r, 5).value),
                "error_description": _build_error_desc(ct, zh, en, _clean(ws.cell(r, 5).value)),
                "metadata":          _parse_metadata(c6),
                "file_name":         fn,
                "segment_id":        sid,
                "annotation":        annotation,
            })

    wb.close()
    return rows


# ══════════════════════════════════════════════════════════════════════════════
# Filter
# ══════════════════════════════════════════════════════════════════════════════

def filter_xlsx(src_path: str, keep_rows: set[int], dst_path: str = "") -> str:
    """Delete data rows NOT in keep_rows. Saves to dst_path (default: _filtered.xlsx).

    Returns output path.
    """
    if not dst_path:
        base, ext = os.path.splitext(src_path)
        dst_path = f"{base}_filtered{ext}"

    wb = openpyxl.load_workbook(src_path)
    ws = _pick_sheet(wb)

    # identify all data rows
    all_data = {r for r in range(11, ws.max_row + 1)
                if _is_data_row(_clean(ws.cell(r, 1).value))}

    to_delete = sorted(all_data - keep_rows, reverse=True)

    if not to_delete:
        print(f"[xbench] Nothing to delete.")
        wb.save(dst_path)
        wb.close()
        return dst_path

    print(f"[xbench] Deleting {len(to_delete)} rows...")

    for rn in to_delete:
        ws.delete_rows(rn)

    # remove orphan group headers
    orphans = _find_orphan_headers(ws)
    for rn in reversed(orphans):
        ws.delete_rows(rn)
    if orphans:
        print(f"[xbench] Removed {len(orphans)} empty group headers.")

    wb.save(dst_path)
    wb.close()
    print(f"[xbench] Saved → {dst_path}")
    return dst_path


# ══════════════════════════════════════════════════════════════════════════════
# JSON cache
# ══════════════════════════════════════════════════════════════════════════════

RAW_DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "raw_data")
os.makedirs(RAW_DATA_DIR, exist_ok=True)


def save_json(rows: list[dict], xlsx_path: str) -> str:
    """Save parsed rows as JSON in data/raw_data/. Returns json path."""
    jp = _json_path(xlsx_path)
    with open(jp, "w", encoding="utf-8") as f:
        json.dump(rows, f, ensure_ascii=False, indent=2)
    return jp


def load_json(xlsx_path: str) -> list[dict]:
    """Load previously saved JSON for a given xlsx path."""
    with open(_json_path(xlsx_path), encoding="utf-8") as f:
        return json.load(f)


def _json_path(xlsx_path: str) -> str:
    base = os.path.splitext(os.path.basename(xlsx_path))[0]
    return os.path.join(RAW_DATA_DIR, f"{base}.json")


# ══════════════════════════════════════════════════════════════════════════════
# Internals
# ══════════════════════════════════════════════════════════════════════════════

def _pick_sheet(wb):
    for sn in wb.sheetnames:
        if "xbench" in sn.lower() or "qa" in sn.lower():
            return wb[sn]
    return wb[wb.sheetnames[0]]


def _parse_group_header(a: str) -> tuple[str, str, str]:
    m = _RE_TERM_PAIR.search(a)
    zh, en = "", ""
    ct = a
    if m:
        inner = m.group()[1:-1]
        parts = [p.strip() for p in inner.split("/", 1)]
        if len(parts) == 2:
            zh, en = parts
        ct = a[:m.start()].strip()
    return ct, zh, en


def _parse_data_row_a(a: str) -> tuple[str, int]:
    m = re.search(r"(.+)\s+\((\d+)\)$", a)
    if m:
        return m.group(1).strip(), int(m.group(2))
    return a, 0


def _build_error_desc(check_type: str, term_zh: str, term_en: str, raw_comment: str) -> str:
    """Build error_description for RAG retrieval.

    Key Term Mismatch: use group-header term pair directly (原文术语 | 术语表术语).
    Other types: use cleaned comment as-is.
    """
    if check_type == "Key Term Mismatch" and term_zh and term_en:
        return f"{term_zh} | {term_en}"
    return _clean_comments(raw_comment)


def _clean_comments(raw: str) -> str:
    """Extract glossary terms from <bxbench> markup.

    Input:  <bxbench>zh_CN:</bxbench> 区域\n<bxbench>en_US:</bxbench> Region
    Output: 区域 | Region
    """
    if not raw:
        return ""
    parts = re.findall(r"</bxbench>\s*(.+)", raw)
    if parts:
        return " | ".join(p.strip() for p in parts)
    return re.sub(r"<[^>]+>", "", raw).strip()


def _parse_metadata(raw: str) -> dict:
    result: dict[str, str] = {}
    if not raw:
        return result
    for line in raw.splitlines():
        line = line.strip()
        if not line:
            continue
        if ":" in line:
            k, v = line.split(":", 1)
            result[k.strip().lower().replace(" ", "_")] = v.strip()
        elif "%" in line or "translated" in line.lower():
            result["match_pct"] = line
    return result


def _find_orphan_headers(ws) -> list[int]:
    """Group headers with zero data rows after them."""
    orphans = []
    for r in range(11, ws.max_row + 1):
        a = _clean(ws.cell(r, 1).value)
        if not _is_group_header(a):
            continue
        has_data = False
        for r2 in range(r + 1, ws.max_row + 1):
            a2 = _clean(ws.cell(r2, 1).value)
            if _is_group_header(a2):
                break
            if _is_data_row(a2):
                has_data = True
                break
        if not has_data:
            orphans.append(r)
    return orphans


# ══════════════════════════════════════════════════════════════════════════════
# CLI
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    import io, json
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
    if len(sys.argv) < 2:
        print("Usage: python xbench.py <file.xlsx> [--import] [--annotator 姓名] [--keep 12,15,20] [--save-json] [--export-queries <out.json>]")
        sys.exit(1)

    path = sys.argv[1]

    if "--from-json" in sys.argv:
        idx = sys.argv.index("--from-json")
        with open(sys.argv[idx + 1], encoding="utf-8") as f:
            rows = json.load(f)
    else:
        rows = parse(path)

    if "--save-json" in sys.argv:
        json_path = _json_path(path)
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(rows, f, ensure_ascii=False, indent=2)
        print(f"Saved → {json_path} ({len(rows)} rows)")

    if "--export-queries" in sys.argv:
        idx = sys.argv.index("--export-queries")
        out_path = sys.argv[idx + 1]
        queries = []
        for r in rows:
            desc = r["error_description"].strip()
            if not desc:
                continue
            gt = "真错误" if r.get("annotation") == "已修改" else "误报"
            queries.append({
                "error_type":        r["check_type"],
                "error_description": desc,
                "source_text":       r.get("source_text", ""),
                "target_text":       r.get("target_text", ""),
                "ground_truth":      gt,
            })
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(queries, f, ensure_ascii=False, indent=2)
        te = sum(1 for q in queries if q["ground_truth"] == "真错误")
        fp = sum(1 for q in queries if q["ground_truth"] == "误报")
        print(f"Exported {len(queries)} queries (真错误: {te}, 误报: {fp}) → {out_path}")

    elif "--keep" in sys.argv:
        idx = sys.argv.index("--keep")
        keep = {int(x.strip()) for x in sys.argv[idx + 1].split(",")}
        filter_xlsx(path, keep)

    elif "--import" in sys.argv:
        annotator = sys.argv[sys.argv.index("--annotator") + 1] if "--annotator" in sys.argv else "宋莹莹"
        from rag.store import init_db, Case, insert_cases_batch
        cases, skipped = [], 0
        for r in rows:
            desc = r["error_description"].strip()
            if not desc:
                skipped += 1
                continue
            cases.append(Case(
                error_type=r["check_type"],
                error_description=desc,
                source_text=r.get("source_text", ""),
                target_text=r.get("target_text", ""),
                review_label="误报",
                annotator=annotator,
                reason="",
            ))
        print(f"[import] {len(cases)} valid cases, {skipped} skipped (empty description)")
        init_db()
        ids = insert_cases_batch(cases)
        print(f"[import] Done. Inserted {len(ids)} cases, IDs {ids[0]}–{ids[-1]}")

    elif "--from-json" not in sys.argv or "--save-json" in sys.argv:
        from collections import Counter
        print(f"File:   {os.path.basename(path)}")
        print(f"Rows:   {len(rows)}")
        ct = Counter(r["check_type"] for r in rows)
        for k, v in ct.most_common():
            print(f"  {k}: {v}")
